import type { LucideIcon } from "lucide-react";
import {
  AlarmClock,
  Ambulance,
  Backpack,
  BadgeCheck,
  BaggageClaim,
  Bike,
  BriefcaseBusiness,
  Building2,
  Bus,
  Cake,
  CalendarDays,
  Camera,
  Car,
  Church,
  Cloud,
  CloudRain,
  Coins,
  Dumbbell,
  Flame,
  FlaskConical,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Handbag,
  Headphones,
  Heart,
  Hotel,
  House,
  ImageIcon,
  Lamp,
  LayoutGrid,
  Leaf,
  Library,
  ListTodo,
  Megaphone,
  Moon,
  MoonStar,
  Music,
  Palette,
  Pill,
  Plane,
  Rocket,
  School,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Sofa,
  Soup,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  Sun,
  Tent,
  Train,
  TramFront,
  Truck,
  Tv,
  Umbrella,
  UserRound,
  Utensils,
  Wallet,
  Watch,
  Waves,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";

export const brickIconMap: Record<string, LucideIcon> = {
  default: LayoutGrid,
  "layout-grid": LayoutGrid,
  grid: LayoutGrid,

  home: House,
  house: House,
  work: BriefcaseBusiness,
  briefcase: BriefcaseBusiness,
  school: GraduationCap,
  graduation: GraduationCap,
  personal: UserRound,
  user: UserRound,
  sport: Dumbbell,
  gym: Dumbbell,
  "list-todo": ListTodo,

  sun: Sun,
  moon: Moon,
  "moon-star": MoonStar,
  cloud: Cloud,
  "cloud-rain": CloudRain,
  leaf: Leaf,
  tree: Leaf,
  star: Star,
  sparkles: Sparkles,
  heart: Heart,
  smile: BadgeCheck,
  crown: Star,
  gift: Gift,

  calendar: CalendarDays,
  alarm: AlarmClock,
  watch: Watch,
  camera: Camera,
  image: ImageIcon,
  tv: Tv,
  music: Music,
  gamepad: Gamepad2,
  palette: Palette,
  monitor: Tv,
  video: Camera,
  speaker: Megaphone,

  shopping: ShoppingCart,
  "shopping-bag": ShoppingBag,
  handbag: Handbag,
  store: Store,
  wallet: Wallet,
  coins: Coins,

  utensils: Utensils,
  soup: Soup,
  cake: Cake,
  wine: Wine,
  headphones: Headphones,

  shirt: Shirt,
  sofa: Sofa,
  lamp: Lamp,

  car: Car,
  bike: Bike,
  bus: Bus,
  train: Train,
  tram: TramFront,
  truck: Truck,
  ambulance: Ambulance,
  plane: Plane,
  rocket: Rocket,

  schoolhouse: School,
  building: Building2,
  church: Church,
  hotel: Hotel,
  tent: Tent,
  backpack: Backpack,
  "baggage-claim": BaggageClaim,

  flask: FlaskConical,
  "flask-2": FlaskConical,
  pill: Pill,
  stethoscope: Stethoscope,

  globe: Globe,
  megaphone: Megaphone,
  badge: BadgeCheck,
  wrench: Wrench,
  flame: Flame,
  zap: Zap,
  umbrella: Umbrella,
  waves: Waves,
};

export const brickIconOptions: Array<{ value: string; label: string; Icon: LucideIcon }> = [
  { value: "layout-grid", label: "Grid", Icon: LayoutGrid },
  { value: "sun", label: "Sun", Icon: Sun },
  { value: "sparkles", label: "Sparkles", Icon: Sparkles },
  { value: "moon", label: "Moon", Icon: Moon },
  { value: "star", label: "Star", Icon: Star },
  { value: "cloud", label: "Cloud", Icon: Cloud },
  { value: "leaf", label: "Leaf", Icon: Leaf },
  { value: "cloud-rain", label: "Rain", Icon: CloudRain },
  { value: "home", label: "Home", Icon: House },
  { value: "work", label: "Work", Icon: BriefcaseBusiness },
  { value: "shopping", label: "Cart", Icon: ShoppingCart },
  { value: "bike", label: "Bike", Icon: Bike },
  { value: "coins", label: "Coins", Icon: Coins },
  { value: "user", label: "User", Icon: UserRound },
  { value: "backpack", label: "Bag", Icon: Backpack },
  { value: "graduation", label: "School", Icon: GraduationCap },
  { value: "umbrella", label: "Umbrella", Icon: Umbrella },
  { value: "shirt", label: "Shirt", Icon: Shirt },
  { value: "flask", label: "Lab", Icon: FlaskConical },
  { value: "sofa", label: "Sofa", Icon: Sofa },
  { value: "lamp", label: "Lamp", Icon: Lamp },
  { value: "zap", label: "Flash", Icon: Zap },
  { value: "image", label: "Photo", Icon: ImageIcon },
  { value: "tree", label: "Nature", Icon: Leaf },
  { value: "gift", label: "Gift", Icon: Gift },
  { value: "palette", label: "Art", Icon: Palette },
  { value: "gamepad", label: "Game", Icon: Gamepad2 },
  { value: "tv", label: "TV", Icon: Tv },
  { value: "music", label: "Music", Icon: Music },
  { value: "wine", label: "Drink", Icon: Wine },
  { value: "utensils", label: "Food", Icon: Utensils },
  { value: "cake", label: "Cake", Icon: Cake },
  { value: "soup", label: "Soup", Icon: Soup },
  { value: "headphones", label: "Audio", Icon: Headphones },
  { value: "library", label: "Books", Icon: Library },
  { value: "megaphone", label: "Megaphone", Icon: Megaphone },
  { value: "alarm", label: "Alarm", Icon: AlarmClock },
  { value: "camera", label: "Camera", Icon: Camera },
  { value: "monitor", label: "Monitor", Icon: Tv },
  { value: "video", label: "Video", Icon: Camera },
  { value: "speaker", label: "Speaker", Icon: Megaphone },
  { value: "heart", label: "Heart", Icon: Heart },
  { value: "flame", label: "Fire", Icon: Flame },
  { value: "crown", label: "Crown", Icon: Star },
  { value: "smile", label: "Smile", Icon: BadgeCheck },
  { value: "building", label: "Building", Icon: Building2 },
  { value: "church", label: "Church", Icon: Church },
  { value: "schoolhouse", label: "School 2", Icon: School },
  { value: "hotel", label: "Hotel", Icon: Hotel },
  { value: "store", label: "Store", Icon: Store },
  { value: "tent", label: "Camp", Icon: Tent },
  { value: "tram", label: "Tram", Icon: TramFront },
  { value: "train", label: "Train", Icon: Train },
  { value: "bus", label: "Bus", Icon: Bus },
  { value: "ambulance", label: "Ambulance", Icon: Ambulance },
  { value: "truck", label: "Truck", Icon: Truck },
  { value: "plane", label: "Plane", Icon: Plane },
  { value: "rocket", label: "Rocket", Icon: Rocket },
  { value: "flask-2", label: "Science", Icon: FlaskConical },
  { value: "pill", label: "Medicine", Icon: Pill },
  { value: "stethoscope", label: "Health", Icon: Stethoscope },
  { value: "globe", label: "World", Icon: Globe },
  { value: "watch", label: "Watch", Icon: Watch },
  { value: "wrench", label: "Tools", Icon: Wrench },
  { value: "calendar", label: "Calendar", Icon: CalendarDays },
  { value: "shopping-bag", label: "Shop", Icon: ShoppingBag },
  { value: "handbag", label: "Handbag", Icon: Handbag },
  { value: "wallet", label: "Wallet", Icon: Wallet },
  { value: "moon-star", label: "Night", Icon: MoonStar },
  { value: "baggage-claim", label: "Travel", Icon: BaggageClaim },
  { value: "waves", label: "Waves", Icon: Waves },
];
